spring:
  profiles:
    active: local

---

spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashop
    username: sa
    password:
    driver-class-name: org.h2.Driver


  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        # show_sql: true # system.out 에 출력
        default_batch_fetch_size: 1000 # IN query 갯수
    # open-in-view: false
    # admin 서비스 처럼 커넥션을 몇개 안쓰는 애플리케이션은 open-in-view 속성을 켜도 되지만
    # 고객 관련 애플리케이션 처럼 트래픽이 많이 걸리고 커넥션이 많이 소비되는 서비스는 false로 사용하는 것이 좋다.


logging:
  level:
    org.hibernate.SQL: debug # logger에 출력
#    org.hibernate.type: trace # 쿼리 파라미터 로그 남기기